begin;

insert into public.deal_snapshots (
  id,
  source,
  source_listing_id,
  url,
  title,
  description,
  category,
  item_price,
  shipping_cost,
  minimum_purchase,
  estimated_landed_cost,
  condition,
  seller_name,
  seller_confidence,
  city,
  state,
  distance_miles,
  pickup_available,
  capacity_gb,
  form_factor,
  interface,
  warnings,
  evidence,
  observed_at,
  expires_at,
  active
)
values
(
  '8ca4b1ad-22de-4d9f-8cb8-dcb1144ebc67',
  'craigslist',
  '7944855670',
  'https://seattle.craigslist.org/est/sop/d/redmond-lightly-used-tb-and-512gb-nvme/7944855670.html',
  '1TB various-brand PCIe 3 NVMe M.2 SSD',
  'Seller lists lightly used 1TB PCIe 3 NVMe drives from $60 with a $100 minimum purchase.',
  'Internal SSD',
  60.00,
  0.00,
  100.00,
  100.00,
  'used',
  'Craigslist owner listing',
  72,
  'Redmond',
  'WA',
  24.60,
  true,
  1000,
  'M.2 2280',
  'NVMe PCIe 3.0 x4',
  '["$100 minimum purchase","Used drive; verify SMART health and exact model before paying","Price and inventory can change without notice","Meet locally and follow marketplace safety guidance"]'::jsonb,
  '{"posted":"2026-07-02 22:14","updated":"2026-07-17 16:03","verified_at":"2026-08-02T16:05:00.000Z","advertised_options":{"generic_1tb_pcie3":60,"health_90_plus_1tb_pcie3":70,"samsung_pm981_1tb":80,"samsung_pm981a_1tb":90,"samsung_1tb_pcie4":120},"distance_basis":"Approximate Burien-to-Redmond driving distance"}'::jsonb,
  '2026-08-02T16:05:00.000Z',
  '2026-08-09T23:59:59.000Z',
  true
),
(
  '30bf7187-5391-4472-9a72-e9a0a1c5cf44',
  'bestbuy',
  'JXT65SKRVV',
  'https://www.bestbuy.com/product/huadisk-1tb-m-2-gen4-nvme-ssd-2280-3d-nand-for-ps5-pc-laptops/JXT65SKRVV',
  'HUADISK 1TB M.2 Gen4 NVMe SSD 2280',
  'New 1TB PCIe Gen4 x4 M.2 2280 NVMe SSD advertised with free shipping.',
  'Internal SSD',
  149.99,
  0.00,
  null,
  149.99,
  'new',
  'Best Buy marketplace listing',
  78,
  null,
  null,
  null,
  false,
  1000,
  'M.2 2280',
  'NVMe PCIe 4.0 x4',
  '["Verify current price, seller, shipping, and delivery date at checkout","Product was not yet reviewed when verified","Local pickup is not guaranteed","Retail availability can change without notice"]'::jsonb,
  '{"verified_at":"2026-08-02T16:06:00.000Z","advertised_price":149.99,"advertised_shipping":"free","retailer_search_term":"1tb m.2 nvme"}'::jsonb,
  '2026-08-02T16:06:00.000Z',
  '2026-08-06T23:59:59.000Z',
  true
)
on conflict (source, source_listing_id) do update
set
  url = excluded.url,
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  item_price = excluded.item_price,
  shipping_cost = excluded.shipping_cost,
  minimum_purchase = excluded.minimum_purchase,
  estimated_landed_cost = excluded.estimated_landed_cost,
  condition = excluded.condition,
  seller_name = excluded.seller_name,
  seller_confidence = excluded.seller_confidence,
  city = excluded.city,
  state = excluded.state,
  distance_miles = excluded.distance_miles,
  pickup_available = excluded.pickup_available,
  capacity_gb = excluded.capacity_gb,
  form_factor = excluded.form_factor,
  interface = excluded.interface,
  warnings = excluded.warnings,
  evidence = excluded.evidence,
  observed_at = excluded.observed_at,
  expires_at = excluded.expires_at,
  active = excluded.active,
  updated_at = now();

commit;
